# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64cde84c3c508203022f3b5f0a4b6a061167cacc00c5980c647b530b9be3c52439c82d68d43e990d869ec810ea75c62141d46ab92ce97d640f44b42e1f4f1b1c

test:
  secret_key_base: d47b67a0015926c3a2818bdeb561b800584b2caf81d98e06f3bf006b0695fb3cbd3f92140148f1056c02fa2929e257446d0f1c6a98213011da0d7e354aedb911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
